### ISSUE TITLE
Website offline

### ISSUE THREAD

**Issue by lorenzwalthert** [pre-commit-ci/issues#193] opened 2023-10-23 06:20 UTC
Since yesterday, I can't reach https://pre-commit.ci/. Is that intended? Or a problem on my end?

**Comment by asottile** [comment] 2023-10-23 12:43
I believe this is a duplicate of #192 

cloudflare had a DNS outage which is probably still stuck in cache for you

**Closed as completed by asottile** 2023-10-23 12:43 UTC

**Comment by lorenzwalthert** [comment] 2023-10-23 19:05
Ah… I promise I searched *open* issues with the term “website” -.-
