### ISSUE TITLE
Local hooks

### ISSUE THREAD

**Issue by DownDev** [pre-commit-ci/issues#185] opened 2023-08-29 11:58 UTC
Is there a way to use local hooks?

```
check for merge conflicts................................................Passed
check toml...............................................................Passed
check yaml...............................................................Passed
fix end of files.........................................................Passed
trim trailing whitespace.................................................Passed
isort....................................................................Failed
- hook id: isort
- exit code: 1

Executable `poetry` not found

black....................................................................Failed
- hook id: black
- exit code: 1

Executable `poetry` not found

ruff.....................................................................Failed
- hook id: ruff
- exit code: 1

Executable `poetry` not found
```
im getting such error with [this](https://github.com/Skurczybyki/bot/blob/main/.pre-commit-config.yaml) config

**Comment by asottile** [comment] 2023-08-29 14:13
`language: system` is missing the point of pre-commit in that it requires your contributors to have a particular state set up beyond pre-commit.  if you use the officially supported repos for those three hooks it will work well

this is otherwise a duplicate of #13

**Closed as completed by asottile** 2023-08-29 14:13 UTC
