### ISSUE TITLE
Autoupdate creates broken YAML

### ISSUE THREAD

**Issue by Holzhaus** [pre-commit-ci/issues#235] opened 2024-10-08 18:16 UTC
The pre-commit.ci autoupdater opened a PR with changes that broke the YAML config: https://github.com/sphinx-contrib/multiversion/commit/47938e1a8f433487afdc2ab21f3fdf94068a03f8

It replaced the `commit` stage like this:
```diff
     stages:
-    - commit
+    - Nonepre-commitNone
```

This PR was affected: https://github.com/sphinx-contrib/multiversion/pull/125 (change was correct with force-push).

**Comment by asottile** [comment] 2024-10-08 18:17
this is a duplicate of #234 -- please search next time!

**Closed as completed by asottile** 2024-10-08 18:17 UTC

**Comment by Holzhaus** [comment] 2024-10-08 18:25
Sorry, didn't see it because it was already closed and I didn't expect the issue to be fixed already. Thanks!
