### ISSUE TITLE
Support Helm docs hooks

### ISSUE THREAD

**Issue by gertzakis** [pre-commit-ci/issues#238] opened 2024-12-12 12:28 UTC
We are using the following pre-commit hooks into our CI:
- `helmlint` from `gruntwork-io/pre-commit` 
- `helm-docs` from `norwoodj/helm-docs`

Both those have dependencies that need to be installed first. Unfortunately we cannot do that in pre-commit-ci, and the pipeline is always failing with errors:
- `/pc/clone/Ea0D3eRVTa-ZHY5N-n4OsA/hooks/helmlint.sh: line 154: helm: command not found`
- `Please install helm-docs to run the pre-commit hook! https://github.com/norwoodj/helm-docs#installation`

as shown [here](https://results.pre-commit.ci/run/github/371457897/1734005609.toEdRjU-ScmXfEg0yCEuwA).

Is there a way to install them first so the CI is passing? Do we miss something in our configuration?

**Comment by asottile** [comment] 2024-12-12 15:22
`language: system` and `language: script` are unsupported escape hatches in pre-commit itself and sort of miss the point of the framework (it's supposed to manage the tools for you!).  they're equally unsupported in pre-commit ci 

this is also a duplicate of #13 -- please check around for duplicates next time!

**Closed as completed by asottile** 2024-12-12 15:22 UTC
